#markdown: kramdown

# For related posts
#lsi: true
#highlighter: pygments

permalink: pretty
paginate: 10
paginate_path: "news/page:num"

safe: true

title: The Poisot Lab
subtitle: Numerical and Computational Ecology
author: Timoth√©e Poisot
production_url: http://poisotlab.github.io

